apiVersion: v1
kind: Service # Service for apache
metadata:
  name: service_apache
spec:
  selector:
    app: apache # the selector select all the pods with this label
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80